spring:
  data:
    mongodb:
      username: spring
      password: spring
      host: localhost
      port: 27017
      database: SpringMGDB
  datasource:
    username: root
    password: LeNguyenKhoi21
    url: jdbc:mysql://localhost:3306/mybatics

mybatis:
  mapper-locations: mybatis/mapper/**

logging:
  level:
    com:
      example:
        mybaticsspringbootstarters:
          mapper: trace
    org:
      springframework:
        jdbc:
          datasource:
            DataSourceTransactionManager: trace
        transaction: trace
      mybatis:
        spring:
          transaction: trace


